#!/bin/bash

for i in 1 2 3 4 5 6 7

H2ERest 
	-T 1		Debugging level 1
        -C config	Config file
	-t 250....	Beam
	-S train_data	Train data file
	-H MMF		Input MMF file
	-M hmm		Directory of output MMF file
	-I phones1.mlf 	Phone1.mlf file
	mono.list	Phoneme list

H2Vite
	-T 1		Debugging level 1
        -t 250     	BEAM
        -H MMF          MMF file that is generated by H2ERest
        -S test_data    Test data file
        -i recout.mlf   Output file name
        -w bg.lat       word net (bigram)
        word.ee2.list    Word list with !Enter and !Exit
        mono.list       Phoneme list

H2Results -T 1 -I ../dict/words1.mlf ../dict/word.ee2.list recout$i.mlf >> RESUL
T_ALL
done

whyun@shrimp:~/local_projects/spoken/models$ 

for i in 1 2 3 4 5 6 7
do HResults -T 1 \
	        -I ../mlf/testword.mlf \
	        ../dict/all_dict_no_variation.txt \
	         hmm$i/smalltest1.mlf
done
